/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef common_CONSTANTS_H
#define common_CONSTANTS_H

#include "common_types.h"

namespace Plow {

class commonConstants {
 public:
  commonConstants();

};

extern const commonConstants g_common_constants;

} // namespace

#endif
