/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef plow_CONSTANTS_H
#define plow_CONSTANTS_H

#include "plow_types.h"

namespace Plow {

class plowConstants {
 public:
  plowConstants();

};

extern const plowConstants g_plow_constants;

} // namespace

#endif
